### ISSUE TITLE
Requests are sent to new backends before they are ready

### ISSUE THREAD

**Issue by creepyghost** [mesosphere/marathon-lb#158]
As soon as a backend is started, it is added to haproxy with the status UP and falling. Before a health check or a readiness check can fail, the backend ends up receiving some traffic. Is there a way to make marathon-lb wait for the readiness check of a backend or maybe the entire app before sending traffic to it?

**Comment by brndnmtthws** [comment]
Hmm, are you specifying health checks in Marathon? Backends are normally added _after_ they're healthy.

**Comment by brndnmtthws** [comment]
Oh, you also need to pass the `--health-check` flag to marathon-lb for it to respect health checks.

**Comment by creepyghost** [comment]
So, health checks are treated as readiness checks. Passing the --health-check flag worked. Thanks!

**Comment by andrebeat** [comment]
This is not the behavior I'm observing, on marathon I have both health checks and readiness checks. When performing a deployment on marathon the new instances get healthy pretty fast (1 minute) but the readiness check only passes after about 10 minutes. Marathon deals with this properly, since it waits for the new instances to be **ready** (even though they're already healthy) to kill the old instances. marathon-lb doesn't seem to respect this behavior though, since as soon as the new instances are healthy (and not ready) they get traffic from marathon-lb.
