### ISSUE TITLE
marathon-lb doesn't work weirdly and must restart it.

### ISSUE THREAD

**Issue by tanglianggithub** [mesosphere/marathon-lb#344]
logs as follows.  **one hour** between "fetching apps" and "received event of type failed_health_check_event". and no logs output since then.

2016-10-08 19:37:06,847- DEBUG - reading running config from /marathon-lb/haproxy.cfg
2016-10-08 19:37:06,847- DEBUG - updating tasks finished, took 21.94865846633911 seconds
2016-10-08 19:42:06,848- INFO - condition wait expired
2016-10-08 **19:42:06**,848- INFO - fetching apps
2016-10-08 **20:44:52**,053- INFO - received event of type failed_health_check_event
2016-10-08 20:44:52,053- INFO - received event of type health_status_changed_event

My config:

sse
--marathon
http://*.*.*.*:10000
--group
abc
--skip-validation
--dont-bind-http-https
--log-format
%(asctime)s- %(levelname)s - %(filename)s:%(lineno)d %(message)s

**Comment by brndnmtthws** [comment]
You'll have to provide some more details. What's not working weirdly?

**Comment by tanglianggithub** [comment]
@brndnmtthws  marathon-lb is dead. I must restart it!
haproxy stats is not right. cannot get notified. requests were lose.

**Comment by brndnmtthws** [comment]
I'm not sure how to help you. Try debugging it further? What version are you running. Could it be you're hitting something similar to what's described in #333?

**Comment by tanglianggithub** [comment]
@brndnmtthws  version is 1.4.1

Base on log , marathon-lb stopped in "2016-10-08 19:42:06,848- INFO - fetching apps".
and after one hour, "2016-10-08 20:44:52,053- INFO - received event of type failed_health_check_event
2016-10-08 20:44:52,053- INFO - received event of type health_status_changed_event" logs were printed.

add some connection timeout and read timeout in requests.request().

came across this issues two times already.

**Comment by tanbokan** [comment]
@brndnmtthws  I was @tanglianggithub colleague.I added something about our problems.

We use the scene is marathon and marathon-lb is located in different IDC, the last few days we found that because the IDC fiber is unstabitily, which appeared in marathon-lb can't update the latest configuration from marathon service through sse mode.

We analyze the code and log suspect the **try_reset** thread may stuck in the requests.request method to marathon v2/apps interface:
  **try_reset** -> **condition.wait(300)** -> **do_reset** -> **marathon.list ()** -> **requests.request( marathon/v2/apps)**
 which cause **try_reset** thread can't release  __ condition, and when the next event arrival, the **sse** thread **reset_from_tasks** method can not acquire __condition, so finally both thread in marathon-lb will stuck.
In addition, we use the operating system version is centos7.1 marathon version is v1.4.1 ，code was  updated at October 10

**Comment by brndnmtthws** [comment]
Interesting. Can you try monkey patching MLB with a shorter timeout on the request? Here's an example diff:

```diff
diff --git a/marathon_lb.py b/marathon_lb.py
index d267940..a494618 100755
--- a/marathon_lb.py
+++ b/marathon_lb.py
@@ -179,6 +179,7 @@ class Marathon(object):
                     'Accept': 'application/json',
                     'Content-Type': 'application/json'
                 },
+                timeout=60,
                 **kwargs
             )
```

As per the [requests docs](http://docs.python-requests.org/en/master/user/quickstart/#timeouts), there's actually no timeout on each request by default, so it's certainly possible you might get stuck here. It's also possible it will get stuck elsewhere.

**Comment by brndnmtthws** [comment]
Actually if you can just test the `:set-timeouts` image tag, that should be sufficient.
