### ISSUE TITLE
Make marathon-lb OS agnostic 

### ISSUE THREAD

**Issue by rcsavage** [mesosphere/marathon-lb#415]
The current marathon-lb code base is restricted to Debian environments only as a heavy wrapper around  haproxy.   It needs to be portable so that it can be easily ported to CentOS, Arch Linux, etc.   It is also heavily dependent on tools such as gnugpg2, logrotate, curl, tini, procps, pcre, socat, etc.

Packages like tini, runit, dirmngr, (lua versions), etc.

It really needs to break away from being heavily tied to the OS.

**Comment by brndnmtthws** [comment]
Why should it be?

I'm not trolling, but you'll need to make a strong case since MLB is only distributed as a Docker image (which to some degree includes the 'OS').

**Comment by rcsavage** [comment]
There are alot of reasons as to why MLB should not be tied to a specific OS inside it's container.   Since this is "open source", the end user should be able to freely choose the container OS without having to impact the "application" (in this sense MLB).    MLB seems to be an application that is more of a wrapper around haproxy that heavily uses OS specific utilities to get it's job done, rather than a stand-alone "application".   Being tied to OS specific tools such as "dirmngr", "runit", "Debian specific commands", does not seem to me like it's a stand alone application.   Without "Debian" it's not a functional service.   

The other reasons why, MLB should be portable to other OS's (ie CentOs, ArchLinux, etc), is that for me, ALL of my containers are built on CentOS.   I have a single base container, and then build everything else on top of it.   When I have to perform updates, I only have to updated ONE Base container.    Also my APM, Security, and other toolings which live inside and outside of my containers mostly support CentOS and RHEL distributions.   You'll find this is the case in many large shops.   In my opinion, marathon-lb seems more like a "hack" than a true "app" since it's heavily dependent on Debian to function properly.    

BTW - I have ported this over to a CentOS 7.2 container, but it was not easy.   And everytime you release and update, I have to refactor the crap out of the Dockerfile to support whatever Debian specific things you use.

**Comment by brndnmtthws** [comment]
<img width="424" alt="screen shot 2017-02-03 at 12 23 45 pm" src="https://cloud.githubusercontent.com/assets/3129093/22607258/e448f784-ea0b-11e6-9e79-251179616faa.png">

**Comment by jkoelker** [comment]
The marathon-lb app is just python 3.5+, it will work on any base-os, now the tooling to run marathon-lb in a reproducible manor *in* a container, yes that is tied to debian.

I don't see much point in changing the base image of the container to another distro. Personally I'd rather it be based on alpine since the size would probably be cut in half or so and could be argued that it would speed up deployments, but the benefit of using a container is that the host os can just have a minimal set of dependencies and everything inside the container can be a black box from the viewpoint of the host (not really in practice, but that's the ideal).
