### ISSUE TITLE
Volumes and marathon-lb package

### ISSUE THREAD

**Issue by skonto** [mesosphere/marathon-lb#454]
Is it possible to pass the volume configuration to the marathon-lb package in order to load a ssl certificate?

I tried with `dos package install marathon-lb --options=config.json` but it does not seem to work.
I guess it only accepts the parameters defined for the service although I would expect values to override the container part of the marathon.json.mustache. Any idea?

**Comment by jkoelker** [comment]
@skonto Apologies for the delay in getting to this. I hope you found the answer but here it is for search history sake as well.

Since `marathon-lb` is just a marathon app, to modify the volumes/etc you can do:

```bash
dcos pacakge describe marathon-lb --app --render [--options=options.json] > marathon-lb.json
```
(You only need to include the `--options` if you want to modify the default template)

This will then render a deployment file which you can then edit to add the volumes to (it should already have 1 volume defined there for `/dev/log` so follow that pattern).

Then deploy it:

```bash
dcos marathon app add marathon.json
```
