### ISSUE TITLE
HAProxy 1.8 plans?

### ISSUE THREAD

**Issue by Larry1123** [mesosphere/marathon-lb#521]
I would love to know if the new 1.8 release for haproxy will be getting looked at soon.
If any help would be needed I could see what I could to, likely mostly only testing, not too good with python.

**Comment by vixns** [comment]
https://github.com/mesosphere/marathon-lb/pull/527

**Comment by Larry1123** [comment]
If you have a public docker image with it ready I can test it on the cluster I am running.

**Comment by vixns** [comment]
`docker pull vixns/marathon-lb:hap181`

**Comment by Larry1123** [comment]
As far as I can tell it is working fine, been running for about two hours now. I don't think I have any way to test the new cache, but reloading is working very nice.

**Comment by Larry1123** [comment]
Just want to say that I have been running it since then with no issues. I'm not sure what mesosphere needs to have tested to be able to accept the merge. If they have anything that they need to be looked at to be able to accept this I can see what I can do.

**Comment by justinrlee** [comment]
FYI: I've published both a Docker image (`mesosphere/marathon-lb:v1.12.0-beta-1`) and a Universe package (`beta-marathon-lb`).  Huge thanks to @vixns for this.

I think the biggest concern is that users that have custom HAPROXY_HEAD may run into issues.  I've added some very basic logic to handle this, but ideally you should update your HAPROXY_HEAD to remove the `daemon` property and add `expose-fd-listeners` to your stats socket at the same time you update to this version of Marathon-LB.

I've done some basic load testing and it doesn't seem to drop any packets, but nothing heavy enough to confirm that it improves the ZDD stuff (mostly because I haven't reproduced dropped packets on a reload yet).  Any feedback would be welcome.

**Comment by Larry1123** [comment]
I'll switch from using the docker image @vixns made to that one. I have had no issues myself running it. I was not able to notice any packets get lost from reloads. Have not done long test only say 10k request at a time at 10-20 rps with services going up and down.

**Comment by justinrlee** [comment]
Also fyi - published Docker image `mesosphere/marathon-lb:v1.12.0-1.8.3-beta-1` and Universe/Catalog package `beta-marathon-lb:1.12.0-1.8.3-beta-1`, which has HAProxy 1.8.3
