### ISSUE TITLE
Inaccurate resource recommendation

### ISSUE THREAD

**Issue by mikestaub** [mesosphere/marathon-lb#68]
When I run the command "dcos package install marathon-lb" I get a prompt that says:

We recommend a minimum of 0.5 CPUs and 256 MB of RAM available for the Marathon Service.
Continue installing? [yes/no]

But the actual resources the app requests are 2 CPUs and 1GB of memory. Shouldn't the prompt reflect this?

**Comment by brndnmtthws** [comment]
It's a bit confusing, but that's the difference between the _minimum_ and the _recommended_ values. We recommend 2 CPUs, so that you have one full CPU for HAProxy, and one for the other code (such as `marathon_lb.py`) which runs. It's best not to constrain the resources of an LB through which you route all your traffic.
